---
title: "Flexdashboard_updated"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
data("rest_inspec")
rest_inspec_df = 
  rest_inspec|>
  drop_na()|>
  filter(!is.na(boro) & boro != "Missing")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
#create a bar graph
rest_inspec_df|> 
  group_by(boro, grade) |>
  summarize(n = n()) |>
  plot_ly(x = ~boro, y = ~n, color = ~grade, type = "bar")|>
  layout(
    title = "Bar Chart of Observations by Borough and Grade",
    yaxis = list(title = "Number of Observations"),
    xaxis = list(title = "Borough")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
#create a box plot
rest_inspec_df |>                                   
  plot_ly(y = ~score, color = ~boro, type = "box")|>
  layout(
    title = "Box plot of scores by borough",
    yaxis = list(title = "Scores"),
    xaxis = list(title = "Boroughs")
  )
```

### Chart C

```{r}
# random sample 200 obs from each boro
random_sample= rest_inspec_df |>
  group_by(boro) |>
  sample_n(200)
random_sample|>
  mutate(text_label = str_c("Grade: ", grade, "\nScore: ", score)) |>
  plot_ly(
  y = ~score, x=~boro,color = ~boro, type = "scatter", mode = "markers",text = ~text_label)|>
  layout(
    title = "Scatterplot of scores by borough",
    yaxis = list(title = "Scores"),
    xaxis = list(title = "Boroughs")
  )

```